name: XT-Bot

on:
  workflow_dispatch:      # 允许手动触发
#  schedule:
#    - cron: '20,50 * * * *'  # 每30分钟运行

jobs:
  auto-process:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # 使用你设置的 secret

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create directories
        run: |
          mkdir -p Python/{dataBase,downloads,logs,output}
          mkdir -p TypeScript/{data,logs,resp,tweets}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: |
          cd TypeScript
          bun install

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          cd Python
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SCREEN_NAME: ${{ secrets.SCREEN_NAME }}
        run: |
          cd TypeScript/scripts
          bun run fetch-following.ts
          bun run fetch-home-latest-timeline.ts

      - name: Run X-Bot.py
        run: |
          cd Python/src
          python X-Bot.py

      - name: Run T-Bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          LARK_KEY: ${{ secrets.LARK_KEY }}
        run: |
          cd Python/src
          python T-Bot.py

      - name: Upload Response Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: network-responses-${{ github.run_id }}  # 唯一标识
          path: |
            Python/logs/
            TypeScript/logs/
            TypeScript/resp/
          retention-days: 7  # 自动清理

      - name: Commit and push changes
        run: |
          git add Python/dataBase Python/output TypeScript/data TypeScript/tweets
          git commit -m "chore: update user data [skip ci]" || exit 0
          git push